spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/whatsapp_bot
spring.datasource.username=root
spring.datasource.password=Karan@2000

whatsapp.token=EAAZCvZBgHL3CoBRUL6GXoFSZBSQhekw9zZAMcSr7Q9Gk7LiZCU3MZAdow0jULNSCASiVVbJg9YZAMQkHfUlZCx6kI3EHdvP3TIlrXWgjqsYul6JtKTC7FwZCj1Cpl39fZAJZAdzauj6awaOkpvRah6ZCDjkUBuDrMsZBjhqAcVkJCt2FtvaqXa3wxfaI5tjdNsApLO2JhBzFFb4XOjbVTgl3dihZAKZCqRAo3biOhqZAZCG0D9FlA3A6rgkS5uRj8GUbnZA7CPL3enlXvxhP0qgMfI4vgPLYtNQq0FUDixarf3AwZDZD
whatsapp.phone-number-id=1105860942608516
whatsapp.verify-token=my_verify_token



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080