spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/whatsapp_bot
spring.datasource.username=root
spring.datasource.password=Karan@2000

whatsapp.token=EAAZCvZBgHL3CoBReKJSJnoLrdVMeWwyCmPpiklSv3MApxJDznzfyvCeeZBBiXn80YBSLShaFEZAk7enoYelVi5fQKHMRL3shvpQhuCZBg3NuIofbdOHmuKuKiceJkgZBnKnjoAOZALcMIACkCWFhQ4HzvgzIGpHO9U7eCvkvo0rlsGj8UiSrefC5BNpKOFcVAZDZD
whatsapp.phone-number-id=1105860942608516
whatsapp.verify-token=my_verify_token



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080